name: publish to npm and cdn

permissions: write-all

on:
  push:
    tags:
      - 'v*'

jobs:

  publishAndRelease:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm i -g pnpm@9.12.2
      - run: pnpm i
      - run: pnpm build

      - name: publish npm
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: aef05d9551634571091c0958c9d65c9c
          projectName: scu-pe-ans
          directory: ./dist
          branch: master

      - name: Zip
        run: zip -r output.zip dist

      - name: Get version number
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release ${{ env.VERSION }}
          files: |
            ./output.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
